### ISSUE TITLE
Pinning to specific phpstan versions with image tags does not work

### ISSUE THREAD

**Issue by stof** [OskarStark/phpstan-ga#31]
see https://github.com/async-aws/aws/runs/749139572?check_suite_focus=true#step:5:1
It installs version 0.12.23 of your docker image, but still gets 0.12.26 of phpstan inside it.

This is because your Dockerfile uses a semver range (`^0.12.23` at the time of the 0.12.23 tag) to install phpstan. And so the selected version might be newer if the build runs after a newer version is released.

**Comment by OskarStark** [comment]
You mean this could fix the problem?

```diff
-RUN composer global require phpstan/phpstan ^0.12.27 \
+RUN composer global require phpstan/phpstan 0.12.27 \
    && composer global require phpstan/extension-installer \
    && composer global require phpstan/phpstan-doctrine \
    && composer global require phpstan/phpstan-phpunit \
    && composer global require phpstan/phpstan-nette \
    && composer global require phpstan/phpstan-symfony \
    && composer global require phpstan/phpstan-mockery \
    && composer global require phpstan/phpstan-webmozart-assert \
    && composer global show | grep phpstan
```

**Comment by OskarStark** [comment]
I did this for the current `0.12.28` release, let's see if it works.

**Comment by Nyholm** [comment]
PR #32 will do this automatically.

How is docker configured to build? Is there an integration from Dockerhub to build every time we push to this repo?

**Comment by stof** [comment]
@OskarStark yes, this diff should fix it.

Btw, to have a reproducible build, you might want to specify versions for extensions too.

**Comment by OskarStark** [comment]
> How is docker configured to build? Is there an integration from Dockerhub to build every time we push to this repo?

Yes, this is setup on dockerhub 👍 

![Screenshot 2020-06-10 13 05 08](https://user-images.githubusercontent.com/995707/84260862-0552ca80-ab1b-11ea-97f6-a561b2b0e691.png)

**Comment by OskarStark** [comment]
> Btw, to have a reproducible build, you might want to specify versions for extensions too.

Makes sense. @Nyholm could you extend your script for the extensions, too?

**Comment by GrahamCampbell** [comment]
This is still broken, as of today:

![image](https://user-images.githubusercontent.com/2829600/87225870-0aa86c80-c388-11ea-993b-91f2968809f1.png)

https://github.com/guzzle/guzzle/runs/860890068?check_suite_focus=true

**Comment by OskarStark** [comment]
I guess it’s an old version an I never rebuild them 🤨

**Comment by OskarStark** [comment]
@GrahamCampbell when I run this locally on my machine:
`docker run --rm -it -w=/app -v ${PWD}:/app oskarstark/phpstan-ga:0.12.28 analyse src/ --level=7`

I get the correct version:
```
Unable to find image 'oskarstark/phpstan-ga:0.12.28' locally
0.12.28: Pulling from oskarstark/phpstan-ga
cbdbe7a5bc2a: Pull complete
1bc86e4cff5f: Pull complete
7be142bd33f5: Pull complete
8132c9e52be3: Pull complete
a137357f3ccd: Pull complete
d20a867f685c: Pull complete
5cb708ec8e9a: Pull complete
a1227942f5ac: Pull complete
1d6944957145: Pull complete
60c049c518c9: Pull complete
4690b76728f3: Pull complete
8b7914baf5ce: Pull complete
6ee9c86d187d: Pull complete
a523f0cf4efe: Pull complete
Digest: sha256:36477d0095a77f8fef0fccf7739ad42733afde23562c0372610e0e312982db78
Status: Downloaded newer image for oskarstark/phpstan-ga:0.12.28
PHPStan - PHP Static Analysis Tool 0.12.28
```

Maybe its a GithubActions caching issue? 🤔

**Comment by Nyholm** [comment]
I like to bump this. 

https://github.com/guzzle/guzzle/pull/2729/checks?check_run_id=1137865008

I ask for 0.12.31 and get 0.12.42

<img width="698" alt="Screenshot 2020-09-19 at 15 18 35" src="https://user-images.githubusercontent.com/1275206/93668218-6d566c80-fa8b-11ea-9979-b817082d46ce.png">

**Comment by OskarStark** [comment]
This is strange, what happens when you run it locally like described in the README?

I am also available on Monday, so we can have chat and try to fix this if you like 👍🏻

**Comment by OskarStark** [comment]
Maybe it's because of an old version? Can you try requesting 0.12.40 for example?

I didn't re-tag older images 🧐

**Comment by Nyholm** [comment]
When I run it locally it works. =)

Tried with 0.12.32, 0.12.40 and 0.12.41. 

```
❯ docker run --rm -it -e REQUIRE_DEV=true -v ${PWD}:/app -w /app oskarstark/phpstan-ga:0.12.41 --version
```

Hm..

**Comment by OskarStark** [comment]
Could it be that GitHub action is using (for some reason) the Dockerfile instead of the ready to use docker image? 
That would explain the story

**Comment by Nyholm** [comment]
Yeah. Something like that. But shouldn’t they use the Dockerfile of the tagged version?

**Comment by OskarStark** [comment]
Yes they should

**Comment by OskarStark** [comment]
@localheinz do you have any clue what's wrong here?

@Nyholm can you please post your full workflow (at least the part for this action)? Thanks

**Comment by Nyholm** [comment]
It is not fancy. 

```yaml
name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHPStan
        uses: OskarStark/phpstan-ga@0.12.31
        env:
          REQUIRE_DEV: true
        with:
          args: analyze --no-progress

```

**Comment by GrahamCampbell** [comment]
0.12.42 tag seems broken on docker hub too.

**Comment by OskarStark** [comment]
@Nyholm what happens if you use:
```diff
- OskarStark/phpstan-ga@0.12.31
+ uses: docker://oskarstark/phpstan-ga@0.12.31
```

**Comment by Nyholm** [comment]
That works!
 

(Slightly changed the syntax)
 ```diff
 - OskarStark/phpstan-ga@0.12.31
 + uses: docker://oskarstark/phpstan-ga:0.12.31
 ```

**Comment by Nyholm** [comment]
I think I found the error!

On all versions of this repo we have not changed the version here: 
https://github.com/OskarStark/phpstan-ga/blob/master/action.yml#L15

**Comment by OskarStark** [comment]
So we need to update it there too? 🤔

**Comment by GrahamCampbell** [comment]
Yeh, otherwise the "latest" version is always pulled.

**Comment by garak** [comment]
It looks like the version in action.yml is changing now.
If so, this issue should be closed
